### ISSUE TITLE
Mô tả web

### ISSUE THREAD

**Issue by 0xTOHO** [KhanhNguyen9872/KhanhNguyen9872.github.io#1]
Web như cc

**Comment by KhanhNguyen9872** [comment]
> Web như cc

=)))) web có bỏ cái gì đâu mà chửi

**Comment by 0xTOHO** [comment]
bỏ file này vào
[index.zip](https://github.com/KhanhNguyen9872/KhanhNguyen9872.github.io/files/11217622/index.zip)
